# Text Analysis Configuration
settings:
  chunk_size: 1000
  language: auto
  num_workers: 4
  similarity_threshold: 0.7
  top_n_words: 100
  output_dir: ./results

# Intent examples for analysis
intent_examples:
  question:
    - ""
      
  complaint:
    - "This doesn't work properly"
    - "I'm having an issue with this product"
    - "I want to return this item because it's defective"
    - "Это не работает должным образом"
    - "У меня проблема с этим продуктом"
    - "Я хочу вернуть этот товар, потому что он неисправен"
      
  suggestion:
    - "It would be better if you could add"
    - "I suggest improving"
    - "You should consider adding"
    - "Напишите актуальный номер телефона для связи с Вами, пожалуйста."
    - "Я предлагаю улучшить"
    - "Вам следует рассмотреть возможность добавления"

# Files to process
files:
  - path/to/feedback.txt
  - path/to/reviews.csv
  - path/to/customer_emails.xlsx
